### PR TITLE
IA-581 add locale to user profile

### PR DESCRIPTION
**Pull request by quang-le**
## Changes

- Fixed bug in `InputComponent` (type: radio)
- Added "Language" Tab in `UsersDialog`
- Added `language` property in `Profile` (profile.py)
- The language option set in `UsersDialog` will override the browser language, but not the language set by the user in the current session (i.e: the one stored in localStorage).
- Added tests for `ProtectedRoute` and `UsersDialog`

https://user-images.githubusercontent.com/38907762/121203086-1d684180-c876-11eb-86fa-3e5cbf178014.mov

### CODE REVIEW

**Review by olethanh — APPROVED** [review]
The python side look ok for me

**Comment by olethanh** [comment]
on the Frontend side we already have nice string when the user select, can we reuse them instead of just "fr" and "en"? 

also curious why another tab and not a dropdown

**Comment by quang-le** [comment]
> on the Frontend side we already have nice string when the user select, can we reuse them instead of just "fr" and "en"?
> 
> also curious why another tab and not a dropdown

You mean a drop down in the first tab? I didn't think about it to be honest, it might be better than an almost empty tab

**Comment by olethanh** [comment]
yes that's what I meant

**Comment by quang-le** [comment]
## Update

- Replaced tab with a dropdown list in the Infos tab
- Added tests for UsersInfos


https://user-images.githubusercontent.com/38907762/121345692-75aa4c80-c925-11eb-82a3-6ff2939b1093.mov

**Pull request merged**
