### PR TITLE
Extend timeout in Elasticbean to 5 minutes

### PR DESCRIPTION
**Pull request by olethanh**
should resould our timeout problem
not extremely confident about it since it don't know ElasticBean much
followed the instruction at
https://medium.com/tomincode/extending-gateway-timeouts-with-node-js-elastic-beanstalk-applications-5cb256f08f4b

### CODE REVIEW

**Comment by olethanh** [comment]
If we do this we also need to modify it via in the load blancers, don't know if that's handled by Terraform or manually

>  Finally, unless you’re only running a single instance, you need to tell ELB (Elastic Load Balancer) to keep the connection open longer. You can do this from the EC2 configuration panel. Find Load Balancers in the sidebar, select the load balancer in front of your application (you can use the Instances tab to identify which balancer you need) and at the bottom of the Description tab, hit the Edit idle timeout button to up your timeout.

**Comment by madewulf** [comment]
Easiest way to try is to deploy that branch on staging.

**Comment by madewulf** [comment]
This fails when deploying: 

Logs are: 

[Thu Jun 17 05:15:15.752577 2021] [:error] [pid 9073] [remote 172.31.39.163:212] mod_wsgi (pid=9073): Target WSGI script '/opt/python/current/app/hat/wsgi.py' cannot be loaded as Python module.
[Thu Jun 17 05:15:15.752618 2021] [:error] [pid 9073] [remote 172.31.39.163:212] mod_wsgi (pid=9073): Exception occurred processing WSGI script '/opt/python/current/app/hat/wsgi.py'.
[Thu Jun 17 05:15:15.752723 2021] [:error] [pid 9073] [remote 172.31.39.163:212] Traceback (most recent call last):
[Thu Jun 17 05:15:15.752753 2021] [:error] [pid 9073] [remote 172.31.39.163:212]   File "/opt/python/current/app/hat/wsgi.py", line 15, in <module>
[Thu Jun 17 05:15:15.752756 2021] [:error] [pid 9073] [remote 172.31.39.163:212]     application = get_wsgi_application()
[Thu Jun 17 05:15:15.752760 2021] [:error] [pid 9073] [remote 172.31.39.163:212]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Jun 17 05:15:15.752763 2021] [:error] [pid 9073] [remote 172.31.39.163:212]     django.setup(set_prefix=False)
[Thu Jun 17 05:15:15.752767 2021] [:error] [pid 9073] [remote 172.31.39.163:212]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
[Thu Jun 17 05:15:15.752770 2021] [:error] [pid 9073] [remote 172.31.39.163:212]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Jun 17 05:15:15.752774 2021] [:error] [pid 9073] [remote 172.31.39.163:212]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
[Thu Jun 17 05:15:15.752776 2021] [:error] [pid 9073] [remote 172.31.39.163:212]     self._setup(name)
[Thu Jun 17 05:15:15.752780 2021] [:error] [pid 9073] [remote 172.31.39.163:212]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
[Thu Jun 17 05:15:15.752782 2021] [:error] [pid 9073] [remote 172.31.39.163:212]     self._wrapped = Settings(settings_module)
[Thu Jun 17 05:15:15.752786 2021] [:error] [pid 9073] [remote 172.31.39.163:212]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/conf/__init__.py", line 189, in __init__
[Thu Jun 17 05:15:15.752788 2021] [:error] [pid 9073] [remote 172.31.39.163:212]     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
[Thu Jun 17 05:15:15.752801 2021] [:error] [pid 9073] [remote 172.31.39.163:212] django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by olethanh** [comment]
I'm seeing this in the deploy log
```
 2021-06-17 05:06:15    ERROR   [Instance: i-0216d3686039ae8a2] Command failed on instance. Return code: 2 Output: sed: can't read /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf: No such file or directory. 
container_command extend_proxy_timeout in .ebextensions/extend-proxy-timeout.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
2021-06-17 05:06:15    INFO    Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
2021-06-17 05:06:15    ERROR   Unsuccessful command execution on instance id(s) 'i-0216d3686039ae8a2'. Aborting the operation.
```

I thought the blog was outdated, but playing around a bit in the VM it seems we are using Apache anyway so there is no chance that would have worked?

**Comment by olethanh** [comment]
New version for Apache.

**Comment by madewulf** [comment]
For this, feel free to deploy on stating untill  it works and the merge

**Comment by olethanh** [comment]
> For this, feel free to deploy on stating until it works and the merge

I already tested it on staging and it was working, didn't you see the message I left you on slack about it?

**Pull request merged**
