### PR TITLE
IA-59 add device list

### PR DESCRIPTION
**Pull request by alfretoine**
**- Monitoring menu is added under admin**

Screenshot 2021-02-18 at 14 19 02

**- Devices are listed using the SingleTable component**

Screenshot 2021-02-18 at 14 18 52

### CODE REVIEW

**Review by beygorghor — CHANGES_REQUESTED** [review]
Same remark as on tasks table: ordering table by columns is active on the table, python code should order data too then. Otherwise disable sort on each column with `sortable: false,`

**Comment by alfretoine** [comment]
> Same remark as on tasks table: ordering table by columns is active on the table, python code should order data too then. Otherwise disable sort on each column with `sortable: false,`

**Comment by alfretoine** [comment]
> Same remark as on tasks table: ordering table by columns is active on the table, python code should order data too then. Otherwise disable sort on each column with `sortable: false,`

Done

**Comment by alfretoine** [comment]
> Same remark as on tasks table: ordering table by columns is active on the table, python code should order data too then. Otherwise disable sort on each column with `sortable: false,`

Done

**Review by beygorghor — APPROVED** [review]

**Pull request merged**
