### PR TITLE
IA-1931: fix(actions): Take a ref for the triggered action to run the cypress tests

### PR DESCRIPTION
**Pull request by qgerome**
Launching cypress test directly on a PR with the comment @cypress is not working properly.

To reproduce, take a branche were tests are passing, checkout the branch,  make a test fail, push and relaunch the tests. They will pass…

Related JIRA tickets : IA-1931

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
A parameter has been added to the inputs of the manual workflow to select the ref to checkout to build the image and run the tests. It fixes the problem where the workflow would checkout the main branch all the times

## How to test

Needs to be merged on main to test

### CODE REVIEW

**Comment by qgerome** [comment]
@cypress

**Comment by qgerome** [comment]
@cypress

**Comment by qgerome** [comment]
@cypress

**Review by olethanh — APPROVED** [review]
Thanks a lot @qgerome lets merge on main  to test then

**Pull request merged**
