### PR TITLE
Create org units group to a campaign

### PR DESCRIPTION
**Pull request by xavierbarbosa**
### Added
- Model that extends from original Group to store groups that belong to a single entity
- Tests for a campaign and storing campaign with groups

Closes https://bluesquare.atlassian.net/browse/IA-563

### CODE REVIEW

**Comment by madewulf** [comment]
Looks fine to me, except for the small formatting problem.

**Comment by madewulf** [comment]
Hi Xavier, 

on many points, this is great, but actually, I would rather have a "tag"  (a text field) added on the existing group than an abstract model and have the default behaviour to ignore all groups without a tag (only showing them if the tag is explicitely mentioned). 

The reason for that is that in the current state, this PR is creating two additional tables, and the groups that are of the new models won't be available in the existing group API, while it would be super nice to be able to filter org units on a given scope and output them in a csv file through the existing org units API.

**Comment by madewulf** [comment]
So you could actually use the present of the tag on the group as you used deleted_at on the forms and have custom accessors. (you learned me that trick :-) )

**Comment by xavierbarbosa** [comment]
Fix the bad merge on a clean branch and PR: https://github.com/BLSQ/iaso/pull/172

**Pull request closed without merging**
