### PR TITLE
IA-1623: add a new workflow to launch cypress tests

### PR DESCRIPTION
**Pull request by codeKameleon**
Explain what problem this PR is resolving

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes

New workflow based on the one we use for cypress manual testing (with comment on a PR). 
I added the event trigger to launch the workflow from github actions with this event : `workflow_dispatch
`
I added a condition to mark the PR and comment only if you triggered the `issue_comment` event by adding a comment with the body : @cypress 

## How to test

Go to [Actions](https://github.com/BLSQ/iaso/actions). In the list of workflows, you should see a new "Cypress Manual Testing" workflow you can click on it.

### CODE REVIEW

**Comment by qgerome** [comment]
You can just update the one already existing to make it runnable under multiple conditions (@cypress + manual trigger)

**Comment by qgerome** [comment]
Also, I'm not sure you can trigger a workflow on a specific branch without adding an input to set the branch (the current dialog only say: "use workflow from <branch>").

**Comment by quang-le** [comment]
Please fill in the template description of your PR so we can understand the choices you made. Otherwise put it back in draft mode

**Comment by codeKameleon** [comment]
@cypress

**Review by qgerome — APPROVED** [review]

**Pull request merged**
