### PR TITLE
IA-419 Create list of tasks

### PR DESCRIPTION
**Pull request by alfretoine**
- Added a menu item under the former 'config' menu, renamed the menu to 'Admin'

Screenshot 2021-01-27 at 19 19 27

- Displays a list of tasks

Screenshot 2021-01-27 at 19 19 16

### CODE REVIEW

**Comment by madewulf** [comment]
Screenshot 2021-01-29 at 12 47 39
I think you hardcoded "lignes copiées"

**Comment by madewulf** [comment]
Also, messages are not displayed: I have one on one of the task, but it's not appearing in the list.

**Comment by madewulf** [comment]
Screenshot 2021-01-29 at 12 51 08
Date de création should appear in any case, even if it's only queued.

**Comment by madewulf** [comment]
You can setup tasks through http://localhost:8081/admin/iaso/task/ to have examples to test your code

**Comment by madewulf** [comment]
I know it was not in the card, but could you add a refresh button to update the status of the task ? Something like this? 
Screenshot 2021-01-29 at 12 55 16

**Comment by alfretoine** [comment]
> Screenshot 2021-01-29 at 12 51 08
> 
> Date de création should appear in any case, even if it's only queued.

Fixed

**Comment by alfretoine** [comment]
> I know it was not in the card, but could you add a refresh button to update the status of the task ? Something like this?
> Screenshot 2021-01-29 at 12 55 16

Added the button

**Comment by alfretoine** [comment]
> Screenshot 2021-01-29 at 12 47 39
> 
> I think you hardcoded "lignes copiées"

Fixed

**Pull request merged**
