### PR TITLE
POLIO-1525 POLIO-1526: Target population

### PR DESCRIPTION
**Pull request by beygorghor**
Target population filed should move from risk assessment  tab to round tab like in the mock-up
Also Calendar popper should display target population , description  + remove budget and vaccine 

Related JIRA tickets : POLIO-1525 POLIO-1526

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- change calendar serializers to return target population per round and campaign description
- move target population filed to round tab
- review calendar popup to add/remove fields

## How to test

- Edit a campaign description and change the target population for a round
- Open calendar and click on the round you just changed
- you should see target population and description on the popup

## Print screen / video

Screenshot 2024-03-26 at 13 20 01
Screenshot 2024-03-26 at 13 16 35

### CODE REVIEW

**Comment by hakifran** [comment]
@beygorghor , I'm not a expert in UX but I have a suggestion on the roundForm. Here is my suggestion:
Screenshot from 2024-04-02 12-21-47

**Comment by lpontis** [comment]
If there is not enough room to have it all together, I can ask if we should move or even remove the mop-up start and end dates. They are never being filled @beygorghor

**Review by hakifran — APPROVED** [review]
The feature seem to me working good and the code seems correct. There is one suggestion I made on the roundForm design

**Comment by beygorghor** [comment]
> @beygorghor , I'm not a expert in UX but I have a suggestion on the roundForm. Here is my suggestion: Screenshot from 2024-04-02 12-21-47


Good point, i'll move back scope his own tab anyway... i merged already this has it is already like that in prod

**Pull request merged**
