### PR TITLE
IA-1629 login  user name is not case senstive

### PR DESCRIPTION
**Pull request by SimonDus**
Explain what problem this PR is resolving

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are there enough tests
## Changes

When creating a new user, to check if the unsername was already existing the check was made on the exact match of the username. So if there was a capital letter or Uppercase etc, the profile API was accepting the username despite the fact that for django backend it would be a duplicate username. So I changed the check and used iexact to ensure the username doesn't exists in a variation ( case insensitive ).

https://user-images.githubusercontent.com/45785235/204291377-8a8cddbd-06c2-4528-9898-f5849285c25f.mov

### CODE REVIEW

**Review by mathvdh — COMMENTED** [review]
Est-ce qu'on a vraiment besoin d'une regex ?

on peut pas utiliser `username__iexact` ou `username__icontains` ??

**Comment by SimonDus** [comment]
> 

icontains marche pas c'est pourquoi j'ai utilisé un regex. Mais effectivement iexact fonctionne aussi, je n'y avais pas pensé.
Les deux fonctionnent.

**Review by mathvdh — APPROVED** [review]
Je suis toujours pour eviter une regex quand c'est possible ;)

**Review by niconoe — APPROVED** [review]
Thanks a lot @SimonDus, great work!

**Pull request merged**
