### PR TITLE
Fix webpack dev server and clean stuff

### PR DESCRIPTION
**Pull request by olethanh**
Do a proper Webpack config with live reloading. It was doing a live reloading before but relied on serie of hacks, replaced it by one single simple hack. This open the door to reactivate hot module replacement in the future.

- pass to npm lock 2.0
- remove react-hot-reloaded as it was not activaed anyway
- remove iaso.server.js do everything in iaso.dev.js
- correctly separate common.js and iaso.js so there is no repetition between the two (common.js was useless before as the dependency were repeated in iaso)
- don't load common.js before being in iaso as it was not used
- remove unused js dependencies: jquery, typescript, ts-loader, husky (please check if there is no mistake there)

NOTE git hooks may complain since I removed husky.  you many need to remove a lot of them. If you don't have your own custom hooks the easied way is to remove all of them, then reinstall the one from pre-commit (python) :
```
rm .git/hooks/*
pre-commit install
```

### CODE REVIEW

**Comment by beygorghor** [comment]
@quang-le, typescript support was added for a futur use in IASO i think ?

**Comment by olethanh** [comment]
> @quang-le, typescript support was added for a futur use in IASO i think ?

would make more sense to add it when we actually use it, that way it's setup with the latest version and practices

**Review by beygorghor — CHANGES_REQUESTED** [review]
Not working for me with `docker-compose up --build`.
Screenshot 2021-08-11 at 10 47 33

**Comment by olethanh** [comment]
the problem should be corrected (no need to rebuild the docker image)

**Review by beygorghor — APPROVED** [review]

**Pull request merged**
