### PR TITLE
IA-3026: prevent loading map tiles if map is not displayed

### PR DESCRIPTION
**Pull request by quang-le**
Explain what problem this PR is resolving

Related JIRA tickets : IA-3026

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
NA

## Changes

- Replaced "hiddenOpacity" class with conditional rendering for map in org unit list and org unit details pages
- Fixed cypress tests

## How to test

- Open browser inspector -> network tab. Make sure to display all, not only XHR
- Go to org units list and search
- Go to map tab: the tiles should only be loaded when switching tabs
- Same operation with org unit detail

## Print screen / video

https://github.com/BLSQ/iaso/assets/38907762/fa61efd1-fdc0-4294-94fa-c61de960f767

### CODE REVIEW

**Comment by madewulf** [comment]
Does this also prevent the download of the org units for the map (as mentioned in the ticket:  "and up to 3000 org units to display on the map") ?

**Review by beygorghor — APPROVED** [review]
Users will loose zoom, selected layer, selected org unit while changing tab. Is this is what we want then ok

**Comment by quang-le** [comment]
> Does this also prevent the download of the org units for the map (as mentioned in the ticket: "and up to 3000 org units to display on the map") ?

No, I think we need to merge the "SingleTable" PR for that

**Comment by quang-le** [comment]
@madewulf @beygorghor  I suggest we remove this from the release and I'll work out a better solution after we've merge the `SingleTable` PR. What do you think?

**Comment by quang-le** [comment]
closing because stale

**Pull request closed without merging**
