### PR TITLE
IA-668: React 17 upgrade

### PR DESCRIPTION
**Pull request by beygorghor**
⚠️ This branch is using https://github.com/BLSQ/bluesquare-components/pull/2 in package.json

Don't forget to remove your node_modules + `npm install` or clean your docker image before

### CODE REVIEW

**Review by kaiobrito — APPROVED** [review]
👍

**Comment by madewulf** [comment]
I would have merge if there were no conflicts :-)

**Comment by olethanh** [comment]
I'm converting it back to draft because before merging we need to merge the bluesquare-component pr and change the dependencies back to the main package

**Comment by quang-le** [comment]
> ⚠️ This branch is using [BLSQ/bluesquare-components#2](https://github.com/BLSQ/bluesquare-components/pull/2) in package.json
> 
> Don't forget to remove your node_modules + `npm install` or clean your docker image before

you can use `npm ci`, it will clean up the node_modules for you and install the deps versions from package-lock

**Comment by quang-le** [comment]
There's deprecated prop in MaterialUI's textarea:

deprecated_prop_comments

**Comment by quang-le** [comment]
When searching for an orgUnit in the form submission screen, the selected orgUnit doesn't display in the 'levels' select boxes

https://user-images.githubusercontent.com/38907762/125085731-31000580-e0cb-11eb-9897-a9dcd70222dc.mov

**Review by quang-le — CHANGES_REQUESTED** [review]
- remove prop deprecation error
- fix select box issue

**Comment by quang-le** [comment]
> ⚠️ This branch is using [BLSQ/bluesquare-components#2](https://github.com/BLSQ/bluesquare-components/pull/2) in package.json
> 
> Don't forget to remove your node_modules + `npm install` or clean your docker image before

The PR in bluesquare-components has been merged

**Review by olethanh — APPROVED** [review]

**Comment by beygorghor** [comment]
Select issue is present on playground too , then not linked to this PR.

**Pull request merged**
