### PR TITLE
IA-1007 Display warning for restricted user

### PR DESCRIPTION
**Pull request by olethanh**
Follow up on IA-987 pr, This a proposal according to Martin suggestion to display a warning to the user when the org unit he can see are restricted.

image

Wholly open to suggestions  on how we can make it look nicer and how to improve the warning  and for a French translation. We can also replicate this in the OrgUnit page

### CODE REVIEW

**Comment by beygorghor** [comment]
I would use a orange snackbar for this, it makes it much more relevant on the page.

**Comment by olethanh** [comment]
isn't it a bit to agressive? also it will be displayed floatting on top of the table at all time

**Comment by beygorghor** [comment]
This the default behaviour we are using everywhere. We can probably create one info snackbar too.

For me your solution is not clear enough, and if you scroll it will disappear

**Comment by olethanh** [comment]
Ok i will try that

**Comment by olethanh** [comment]
finally found the <Alert> in Material UI, I couldn't find it the first time, it was in the snackbar doc ... It make it look much nicer and simplify the code. So I tested the two version, as a warning on top and in a snackbar, personally I prefer on top but snackbar is ok too and I have  no strong preference so it's like you prefer.  Last commit is the one with snackbar.

https://user-images.githubusercontent.com/82500/150765267-8ee5e8a4-3aeb-4f19-80ea-539e6fa9fc78.mp4



https://user-images.githubusercontent.com/82500/150765264-ab05aec6-87d4-4924-ab04-6dc8c8ed5faa.mp4

**Comment by beygorghor** [comment]
As we are using Snackbars for other interaticons with the user, it can be a bit confusing to change the way you are displaying infos. Thanks for the examples, i would go for the snackbar version.

**Review by beygorghor — APPROVED** [review]

**Comment by olethanh** [comment]
TODO: Add close button

**Review by quang-le — APPROVED** [review]
Missing translations added so OK for me

**Pull request merged**
