### PR TITLE
IA-597 add comments to org units

### PR DESCRIPTION
**Pull request by quang-le**
## Features
- Added a "Comments" tab in `/orgunits/lists' in the Map's sidebar
- Same in `/orgunits/detail`
- Also added a "Comments" tab in `orgunits/detail`'s TopBar
- Comments can be replied to to form 1-level deep threads. Replying to a reply will add the comment to the existing thread
- Threads can be expanded and collapsed
- Comment's text is truncated once it reaches a certain length. It can also be collapsed/expanded

## Note
Requires [bluesquare-components' PR to build](https://github.com/BLSQ/bluesquare-components/pull/1)
If the PR hasn't been merged in bluesquare-components, you will need to pull its branch and [depend on it locally](https://github.com/BLSQ/bluesquare-components/blob/main/README.md)

https://user-images.githubusercontent.com/38907762/122572492-15668980-d04e-11eb-86d5-5900808c6a1b.mov

### CODE REVIEW

**Comment by olethanh** [comment]
I would propose to move the Comment as the first tab, before the settings? if everyone is alright with that?

**Comment by madewulf** [comment]
> I would propose to move the Comment as the first tab, before the settings? if everyone is alright with that?

I think that's a good idea.

**Comment by quang-le** [comment]
> > I would propose to move the Comment as the first tab, before the settings? if everyone is alright with that?
> 
> I think that's a good idea.

But after the filters then?

**Comment by quang-le** [comment]
> > > I would propose to move the Comment as the first tab, before the settings? if everyone is alright with that?
> > 
> > 
> > I think that's a good idea.
> 
> But after the filters then?

So, I checked again. It works when you're on the OrgUnit's page: the first tab is filters, the second is Comments. But if you're in the Org Units List page, Comments becomes the first Tab.
So far on that page (Org Units list), we have the Settings selected as default tab (it was  the only one before this PR). So we can either:
- Select comments by default, but in many cases, it won't have any comments, so it's mostly empty space
- Keep the Settings as the first tab in Org units List, but then we don't have a consistent tab order across all screens

**Comment by olethanh** [comment]
set comment as default, not sure the people used the settings much anyway

**Comment by olethanh** [comment]
Minor nitpick but Rather than "Show Thread"  and "Hide Thread" I would rather have "Show reply", or even better "Show 3 replies". 
But we can keep that for V2

**Review by olethanh — APPROVED** [review]

**Pull request merged**
