### PR TITLE
Forgot/reset password

### PR DESCRIPTION
**Pull request by vinch**

### CODE REVIEW

**Comment by vinch** [comment]
Do not merge yet, some styling is still needed.

**Review by olethanh — APPROVED** [review]
Can't comment on the style but the python code is pretty straight forward. Not sure how we want to handle the translation though?

**Comment by vinch** [comment]
> Can't comment on the style but the python code is pretty straight forward. Not sure how we want to handle the translation though?

Good point. Yeah, we need to use translation keys in there. I did it at some places but not everywhere yet.

**Comment by olethanh** [comment]
@beygorghor  I'm guessing you are the best to review the front and style part

**Comment by olethanh** [comment]
Also note that the mail sending is still synchroneous here, it's okay for me for this feature but if we wanted to use this as an excuse to set up the async mail infrastructure it's obviously still missing

**Review by beygorghor — COMMENTED** [review]
May be just add a back to login link on forgot password page.
Also reuse the logo  on top of this page.

Screenshot 2021-06-01 at 11 39 58

**Comment by vinch** [comment]
@beygorghor I added to back to login link but I'm not sure about the logo thing. I purposely removed it from these pages as they are more transactional and the logo didn't have its place there in my opinion. I don't have a strong opinion on this so if you really want to put it back, no problem.

**Review by beygorghor — APPROVED** [review]

**Pull request merged**
