### PR TITLE
Polio-622:improve and refactor the calendar xls export

### PR DESCRIPTION
**Pull request by hakifran**
This PR is about improving and refactor the code of exporting the calendar as a XLSX file

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [x] Are there enough tests
## Changes
- Add some docstring and some type annotations
- Move cell width, height and size into constants
- Unit test that the generated XLSX contains correct data
## How to test
- Run unit tests
- Try export the calendar as a XLSX file

### CODE REVIEW

**Comment by qgerome** [comment]
@cypress

**Comment by qgerome** [comment]
@cypress

**Comment by qgerome** [comment]
@cypress

**Comment by niconoe** [comment]
Hey @hakifran, as you can see in the test_python check, mypy is now run when code is pushed to a PR and there are a few (very minor) problems with your types. I let you fix them as an exercise, but please ping me if you're stuck and we'll have a look together!

**Comment by hakifran** [comment]
> Hey @hakifran, as you can see in the test_python check, mypy is now run when code is pushed to a PR and there are a few (very minor) problems with your types. I let you fix them as an exercise, but please ping me if you're stuck and we'll have a look together!

The problems with types have been fixed

**Comment by niconoe** [comment]
Hey @hakifran, great job! I just made one small improvement to the type hints in tests. You can have a look at my commit: by pre-declaring the variable type, we also avoid the error and that's slighlty better than ignoring the error, since mypy knows (and will be ale to check) the correct type for those two class variables.

**Review by niconoe — APPROVED** [review]
Brilliant job @hakifran, thanks a lot!

**Pull request merged**
