### PR TITLE
POLIO-579: calendar page disable pdf button when map still loading

### PR DESCRIPTION
**Pull request by codeKameleon**
Explain what problem this PR is resolving

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes

- updated the logic inside useEffect to disable pdf and xlsx export buttons if there is no filtered campaigns in the calendar

## How to test

Go to Polio > Calendar
Play with the calendar to see if when there is no data, the buttons are disable and the other way around.

## Print screen / video

https://user-images.githubusercontent.com/25134301/197745763-403a9c8c-8838-400d-8524-a74c22ca07ba.mp4

### CODE REVIEW

**Comment by hakifran** [comment]
@codeKameleon It's good for me! But for the XLSX export it takes the data for the whole year regardless the filteredcampaigns is empty or not, therefore I don't think it's necessary to disable it when the filteredcampaigns not yet filled

**Comment by beygorghor** [comment]
> @codeKameleon It's good for me! But for the XLSX export it takes the data for the whole year regardless the filteredcampaigns is empty or not, therefore I don't think it's necessary to disable it when the filteredcampaigns not yet filled

yes @codeKameleon you can update this please ?

**Review by beygorghor — CHANGES_REQUESTED** [review]
see Frank comment

**Review by hakifran — APPROVED** [review]
Good Job.

**Pull request merged**
