### PR TITLE
IA-777 depths

### PR DESCRIPTION
**Pull request by beygorghor**
- use a pane to put shapes and markers
- adding depth on as_dict since it's in use now for the map (org_unit_type_depth)
- fix small issue with bluesquare-component import

### CODE REVIEW

**Review by quang-le — CHANGES_REQUESTED** [review]
When I test locally, the map is not centered nor zoomed correctly when I click on the map action button in the  org unit search table:

Screenshot 2021-09-21 at 16 44 55

**Review by quang-le — APPROVED** [review]

**Review by madewulf — COMMENTED** [review]
I don't see any effect of the depth change in the details and it does not seem to impact the org unit search either

https://user-images.githubusercontent.com/185797/134377012-3a6ee264-54f0-4bf3-b611-7a5104f9f087.mp4

**Comment by beygorghor** [comment]
2 searches, with config province (4)> zone (3)> aire (2)> village (1)
Screenshot 2021-09-23 at 14 18 39
Screenshot 2021-09-23 at 14 18 34
Screenshot 2021-09-23 at 14 18 24

On detail page
Screenshot 2021-09-23 at 14 18 54

**Comment by quang-le** [comment]
OK for me

**Review by olethanh — APPROVED** [review]

**Pull request merged**
