### PR TITLE
IA-1709 refactor inner drawer to function

### PR DESCRIPTION
**Pull request by quang-le**
Explain what problem this PR is resolving

Related JIRA tickets : IA-1709

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
x

## Changes

- Pretty straightforward refactor:
    - Replace prop types with Props + default value
    - Turn toggle function to callback
    - replace class state with useState
    - use hooks i.o HoC for style and intl 

## How to test

Go to Org Units > Map view
Go to org Unit details > Map view

In both test the side drawer

## Print screen / video
Nothing should change

## Notes

There are typescript errors related to styling. They were there already in other components using the same styles

### CODE REVIEW

**Comment by hakifran** [comment]
@quang-le there is an error on use this location Screenshot from 2024-07-12 11-24-31

**Comment by hakifran** [comment]
@quang-le Everything working fine, apart from the use this location bug. Can we create a new ticket about it or fix it in this PR

**Review by hakifran — APPROVED** [review]
Everything working fine, apart from the use this location bug. Can we create a new ticket about it as it's not related to the current PR or fix it in this PR?

**Review by beygorghor — APPROVED** [review]
An easy one

**Comment by quang-le** [comment]
> Everything working fine, apart from the use this location bug. Can we create a new ticket about it as it's not related to the current PR or fix it in this PR?

It's unrelated to this PR. I have it on main as well. Can you make a ticket please, @hakifran ?

**Pull request merged**
