### PR TITLE
IA-1855: fix docker M1 support

### PR DESCRIPTION
**Pull request by codeKameleon**
docker build was failing at `npm ci `step

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests

## Changes

- updated the debian version in Dockerfile
- updated the platform for webpack in docker-compose.yml

### CODE REVIEW

**Review by beygorghor — APPROVED** [review]

**Comment by beygorghor** [comment]
=> remove webpack image and container run docker-compose build --no-cache  webpack and docker-compose up

**Review by quang-le — CHANGES_REQUESTED** [review]
It builds, but when I start it after merging main, here's what I get:
Screenshot 2023-01-31 at 12 35 40

**Comment by olethanh** [comment]
doesn't build on my computer : 

```
$ docker-compose build webpack
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.webpack: 'platform'
```

**Comment by mathvdh** [comment]
@olethanh est-ce que ça règle ton problème si tu changes le `version` tout en haut du `docker-compose.yml `à `version: "3.7"`

C'est dans la spec de docker compose file : https://github.com/compose-spec/compose-spec/blob/master/spec.md#platform

**Comment by mathvdh** [comment]
@quang-le pour moi ça marche le frontend dans docker avec cette version

**Comment by mathvdh** [comment]
Si ça marche pour @olethanh on peut udpater la version à 3.7 tout au dessus du `docker-compose.yml` et c'est bon pour moi

**Comment by olethanh** [comment]
nope, j'ai peut -être pas la bonne version de docker. qqun d'autre de pas sur mac peux tester?

**Comment by olethanh** [comment]
do you actually need the platform line with the other modification?

**Comment by mathvdh** [comment]
I tried removing the "platform" but it doesn't work on my M1

**Review by olethanh — APPROVED** [review]
I upgraded my docker and it works for me now. Will merge once the deploy is done

**Pull request merged**
