### PR TITLE
IA-663: Set different color for initial district

### PR DESCRIPTION
**Pull request by vieiramanda11**
### Added:

When a district is selected while creating a new campaign, its color will be red.

https://user-images.githubusercontent.com/47039931/126795361-e82c396b-2749-49a7-b9de-81f441472856.mov

### CODE REVIEW

**Comment by quang-le** [comment]
> ### Added:
> 
> When a district is selected while creating a new campaign, its color will be red.
> Gravacao.de.Tela.2021-07-23.as.11.13.34.mov

Maybe use the color from the theme instead: `theme.palette.primary.main`. you can access it by making a `useStyles` hook

**Comment by olethanh** [comment]
I agree on using a softer color, but we can just hard code it, no need to complicate with the useStyle

**Comment by vieiramanda11** [comment]
> I agree on using a softer color, but we can just hard code it, no need to complicate with the useStyle

Currently:

Captura de Tela 2021-07-26 às 11 01 51

Softer:

Captura de Tela 2021-07-26 às 11 05 07

**Review by olethanh — APPROVED** [review]
LGTM will rebase to resolve conflict

**Pull request merged**
