### PR TITLE
Update Node and NPM

### PR DESCRIPTION
**Pull request by geoffreydhuyvetters**
Preparation for a module federation setup

- update Node to latest LST
- update NPM to 7 (to be able to use workspaces)

### CODE REVIEW

**Comment by olethanh** [comment]
```
webpack_1  | 
webpack_1  | added 6 packages, changed 1 package, and audited 1955 packages in 7s
webpack_1  | 
webpack_1  | 24 vulnerabilities (10 moderate, 14 high)
webpack_1  | 
webpack_1  | To address issues that do not require attention, run:
webpack_1  |   npm audit fix
webpack_1  | 
webpack_1  | To address all issues (including breaking changes), run:
webpack_1  |   npm audit fix --force
webpack_1  | 
webpack_1  | Run `npm audit` for details.
webpack_1  | 
webpack_1  | > js@0.1.0 build
webpack_1  | > react-app-rewired build
webpack_1  | 
webpack_1  | Failed to compile.
webpack_1  | 
webpack_1  | EACCES: permission denied, unlink '/opt/app/plugins/polio/static/polio/asset-manifest.json'
```

**Comment by geoffreydhuyvetters** [comment]
Don't think that error has anything to do with my changes in the PR. I just tried it (rebuild the containers and docker-compose up) and works fine here.

**Review by xavierbarbosa — APPROVED** [review]
Looks good, do we need to coordinate with @olethanh or @madewulf to also upgrade the servers to the same version?

**Comment by olethanh** [comment]
@geoffreydhuyvetters you are right it seems it was another error, sorry. I reset everything and it seems to be working now.

**Comment by olethanh** [comment]
I have updated the node version in the workflows (both test and deploy).

Beside the build and automated test passing, we should push this  branch to stage and verify manually that the UI is still working before merging.

**Pull request merged**
