### PR TITLE
POLIO-1003: Frontend: remove surge data from preparedness tab

### PR DESCRIPTION
**Pull request by hakifran**
Explain what problem this PR is resolving
- Surge datas(fields) are not needed anymore
Related JIRA tickets : [POLIO-1003](https://bluesquare.atlassian.net/browse/POLIO-1003)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Remove all field related to surge on frontend

## How to test
- Go to campaigns
- Edit or create a campaign
- Go to Preparedness tab
- Check if the surge field still there

### Before the changes
Screenshot from 2023-04-17 19-04-30
### After the changes
Screenshot from 2023-04-17 19-05-33

[POLIO-1003]: https://bluesquare.atlassian.net/browse/POLIO-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hakifran** [comment]
@cypress

**Comment by hakifran** [comment]
@cypress

**Comment by hakifran** [comment]
@cypress

**Review by codeKameleon — APPROVED** [review]

**Comment by hakifran** [comment]
@cypress

**Comment by beygorghor** [comment]
@hakifran launching cypress tests is not working properly with the comment.
Please use action to launch it

**Review by beygorghor — APPROVED** [review]

**Review by quang-le — APPROVED** [review]

**Pull request merged**
