### PR TITLE
IA-3398 add warning when updating phone number

### PR DESCRIPTION
**Pull request by quang-le**
Explain what problem this PR is resolving

Related JIRA tickets : IA-3398

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
NA

## Changes

- Update `WarningModal` to handle the warning about user permissions and phone number
- Format the messages for `WarningModal`  in `UsersDialog`

## How to test

 Go to iaso > users > managment

open a user
Try and change the phone number

## Print screen / video

https://github.com/user-attachments/assets/f65a5dc2-091a-4910-ab4a-5be1e8b8aa4c

## Notes
merges into https://github.com/BLSQ/iaso/pull/1615

### CODE REVIEW

**Review by beygorghor — APPROVED** [review]

**Review by beygorghor — CHANGES_REQUESTED** [review]
you have missing translations:
Please translate the translation containing CHECKME and remove it.
iaso.users.permAndPhoneWarningTitle
iaso.users.permAndPhoneWarningTitle

**Comment by beygorghor** [comment]
also i had the warning modale while only updating user name:

https://github.com/user-attachments/assets/595cd549-818d-494b-84ad-0bad5b9ef8f7

**Comment by quang-le** [comment]
> also i had the warning modale while only updating user name:
> Screen.Recording.2024-09-11.at.13.31.11.mov

I can't reproduce this one

**Comment by quang-le** [comment]
> > also i had the warning modale while only updating user name:
> > Screen.Recording.2024-09-11.at.13.31.11.mov
> 
> I can't reproduce this one
 I have it now, nevermind. Looking into it

**Review by beygorghor — APPROVED** [review]

**Pull request merged**
