### PR TITLE
IA-3593_IA-3584: Fix org unit favourite image and Add reference submissions for Areas, Districts, Regions, and Country

### PR DESCRIPTION
**Pull request by butofleury**
Explain what problem this PR is resolving

Related JIRA tickets : [IA-3593](https://bluesquare.atlassian.net/browse/IA-3593), [IA-3584](https://bluesquare.atlassian.net/browse/IA-3584)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Associated favorite picture to org unit other than health facilities. 
- Added reference submissions for Areas, Districts, Regions, and Country.

## How to test

From setuper folder, launch setuper via `python3 setuper.py` to generate test data. Then login with the created account and open :

- [Org Units page](http://localhost:8081/dashboard/orgunits/list/): filter on org type other than health facility org unit type. Then open any org unit page  and go on the **IMAGES** tab. You should see a selected image for the org unit.

- [Form Submissions page](http://localhost:8081/dashboard/forms/submissions/):  filter on org type other than health facility org unit type. You should see submission for org unit is selected as reference submission.

## Print screen / video

**1. Favourite image**

[Iaso-associate-favorite-pictures.webm](https://github.com/user-attachments/assets/0d7eb6f6-642c-408d-a5e5-ee4613ea59da)

**2. Reference submission for Areas, Districts, Regions, and Country**

image

[IA-3593]: https://bluesquare.atlassian.net/browse/IA-3593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IA-3584]: https://bluesquare.atlassian.net/browse/IA-3584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by quang-le — CHANGES_REQUESTED** [review]
Looks all good to me. I would just not assign a favorite picture and a reference submission to all org units in order for us to have more possible scenarios when testing.

Other than that, great job as usual

**Comment by butofleury** [comment]
> Looks all good to me. I would just not assign a favorite picture and a reference submission to all org units in order for us to have more possible scenarios when testing.
> 
> Other than that, great job as usual

Maybe he have the both cases(favorite picture and reference submission) because the PR is including 2 tickets(favorite picture and reference submissions for org unit other than health facility). 

@quang-le , if it looks good to you, you can approve it, so it would be possible to merge it.

**Review by quang-le — APPROVED** [review]

**Comment by beygorghor** [comment]
@Fleury, can you please launch a setuper on staging, or point me to an existing one to test it ?  Thank you

**Comment by butofleury** [comment]
> @fleury, can you please launch a setuper on staging, or point me to an existing one to test it ? Thank you

@beygorghor , you can use **fmoogoo** account on [staging](https://iaso-staging.bluesquare.org/) then test :

1. Favourite image from [Org Units page](https://iaso-staging.bluesquare.org/dashboard/orgunits/list/)
2. Reference submission from [Form Submissions page](https://iaso-staging.bluesquare.org/dashboard/forms/submissions/)

**Pull request merged**
